import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./Others/Bsjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BootstrapClient></BootstrapClient>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
