import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./Others/Bootstrap_js";
const inter = Inter({ subsets: ["latin"] });
import { GoogleOAuthProvider } from '@react-oauth/google';

export const metadata = {
  title: "E-Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BootstrapClient></BootstrapClient>
      <body className={inter.className}>
        <GoogleOAuthProvider clientId='166424008698-umf0iijpbmf0he2qdg70ebpbjhv9ol4b.apps.googleusercontent.com'>
          {children}
        </GoogleOAuthProvider>

      </body>
    </html>
  );
}
